chore: codesandbox auto builds (#2062)
* chore: try out codesandbox auto builds

* commit something to trigger deployments

* chore: codesandbox auto builds

set node to v14 because: [!] TypeError: inputSrcs.map(...).flat is not a function

* chore: codesandbox auto builds

use the root directory for publishing, because it contains the package.json

* chore: codesandbox auto builds

let's see if codesandbox picks up the basic example with a leading slash like shown in the docs

* chore: codesandbox auto builds

revert the test commit

* chore: codesandbox auto builds

add basic-typescript example

* chore: codesandbox auto builds

add basic-typescript example to codesandbox builds

* chore: codesandbox auto builds

no-use-before-define

* chore: codesandbox auto builds

don't use exact versions for examples, otherwise, we won't have the latest version when trying them out